name: Update Rolling nightlies Assets

on:
  workflow_dispatch:
  pull_request:
  # push:
  #   branches: [ main ]

permissions:
  contents: write

jobs:
  update-assets:
    runs-on: ubuntu-latest
    steps:
      # Verify that all nightlies have passed and have been built in the last 24 hours
      - name: Verify conditions for update
        run: |
          set -x 
          echo "Verifying conditions for nightlies update";

          THRESHOLD=$(($(date +%s) - 86400))000;

          : # curl needs --globoff to avoid having to escape all brackets in the url
          
          JOB_STATUS=$(curl -u "$GH_USER:$GH_TOKEN" --silent --globoff 'https://ci.ros2.org/api/xml?tree=jobs[name,lastBuild[timestamp,result]]&xpath=/hudson/job[name="packaging_linux"+or+name="packaging_windows"+or+name="packaging_linux-rhel"+or+name="packaging_linux-aarch64"]&wrapper=nightlies')

          while read -r JOB_BLOCK; do

            NAME=$(echo "$JOB_BLOCK" | sed -n 's|.*<name>\(.*\)</name>.*|\1|p')
            RESULT=$(echo "$JOB_BLOCK" | sed -n 's|.*<result>\(.*\)</result>.*|\1|p')
            TS=$(echo "$JOB_BLOCK" | sed -n 's|.*<timestamp>\(.*\)</timestamp>.*|\1|p')

            echo "Checking Job: $NAME..."

            : # If job is still running then it's not possible to do the update
            if [ -z "$RESULT" ]; then
              echo "☁️ Job $NAME is currently in progress or has no result."
              exit 1
            fi

            : # If the a job failed then the update should not happen to keep synchrony between os.
            if [ "$RESULT" = "FAILURE" ]; then
              echo "🌧️ Job $NAME failed with result: $RESULT"
              exit 1
            fi

            : # If the job is older than T-24 then the nightly set has not completed fully yet. 
            if [ "$TS" -lt "$THRESHOLD" ]; then
              echo "☁️  Job $NAME is stale! Last run was > 24h ago (TS: $TS)"
              exit 1
            fi

            echo "☀️ $NAME passed all checks."
          done <<< "$(echo "$JOB_STATUS" | sed 's|<job |\n<job |g')"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USER: ${{secrets.GH_USER}}
      # - name: Download assets
      #   run: |
      #     curl -L "https://example.com/path/to/your/file.zip" -o ./latest-build.zip

      # - name: Ensure Release Exists and Upload
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      #     TAG: "v1.0.0-pre"
      #   run: |
      #     # 1. Check if the release exists. If not, create it.
      #     if ! gh release view "$TAG" >/dev/null 2>&1; then
      #       echo "Release $TAG not found. Creating new pre-release..."
      #       gh release create "$TAG" --prerelease --title "Nightly Pre-release" --notes "Automated build assets."
      #     else
      #       echo "Release $TAG exists. Proceeding to upload."
      #     fi

      #     # 2. Upload and overwrite (clobber) the asset
      #     gh release upload "$TAG" ./latest-build.zip --clobber